"""init

Revision ID: 077ed377263a
Revises: 
Create Date: 2026-05-28 22:19:44.702069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '077ed377263a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('patient_name', sa.String(length=128), nullable=True),
    sa.Column('relationship', sa.String(length=32), nullable=True),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('treatment_date', sa.Date(), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hospital_name', sa.String(length=256), nullable=True),
    sa.Column('is_network_hospital', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('primary_reason', sa.Text(), nullable=True),
    sa.Column('claim_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('claim_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('doc_tag', sa.String(length=64), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('doc_confidence', sa.NUMERIC(precision=4, scale=3), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_traces',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('claim_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('step', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_traces')
    op.drop_table('claim_documents')
    op.drop_table('claims')
    # ### end Alembic commands ###
